telegram:
  token: "${TELEGRAM_BOT_TOKEN}"
  api_base_url: ""
  debug: false
  updates_timeout: 30
  webhook_enable: false
  webhook_url: ""
  webhook_domain: "https://your-domain.com"
  webhook_path: "/webhook"

server:
  address: ":8080"

logging:
  level: "info"

